#pragma once

// From GLFW/glfw3.h
#define PUMPKIN_KEY_SPACE              32
#define PUMPKIN_KEY_APOSTROPHE         39
#define PUMPKIN_KEY_COMMA              44
#define PUMPKIN_KEY_MINUS              45
#define PUMPKIN_KEY_PERIOD             46
#define PUMPKIN_KEY_SLASH              47
#define PUMPKIN_KEY_0                  48
#define PUMPKIN_KEY_1                  49
#define PUMPKIN_KEY_2                  50
#define PUMPKIN_KEY_3                  51
#define PUMPKIN_KEY_4                  52
#define PUMPKIN_KEY_5                  53
#define PUMPKIN_KEY_6                  54
#define PUMPKIN_KEY_7                  55
#define PUMPKIN_KEY_8                  56
#define PUMPKIN_KEY_9                  57
#define PUMPKIN_KEY_SEMICOLON          59
#define PUMPKIN_KEY_EQUAL              61
#define PUMPKIN_KEY_A                  65
#define PUMPKIN_KEY_B                  66
#define PUMPKIN_KEY_C                  67
#define PUMPKIN_KEY_D                  68
#define PUMPKIN_KEY_E                  69
#define PUMPKIN_KEY_F                  70
#define PUMPKIN_KEY_G                  71
#define PUMPKIN_KEY_H                  72
#define PUMPKIN_KEY_I                  73
#define PUMPKIN_KEY_J                  74
#define PUMPKIN_KEY_K                  75
#define PUMPKIN_KEY_L                  76
#define PUMPKIN_KEY_M                  77
#define PUMPKIN_KEY_N                  78
#define PUMPKIN_KEY_O                  79
#define PUMPKIN_KEY_P                  80
#define PUMPKIN_KEY_Q                  81
#define PUMPKIN_KEY_R                  82
#define PUMPKIN_KEY_S                  83
#define PUMPKIN_KEY_T                  84
#define PUMPKIN_KEY_U                  85
#define PUMPKIN_KEY_V                  86
#define PUMPKIN_KEY_W                  87
#define PUMPKIN_KEY_X                  88
#define PUMPKIN_KEY_Y                  89
#define PUMPKIN_KEY_Z                  90
#define PUMPKIN_KEY_LEFT_BRACKET       91
#define PUMPKIN_KEY_BACKSLASH          92
#define PUMPKIN_KEY_RIGHT_BRACKET      93
#define PUMPKIN_KEY_GRAVE_ACCENT       96
#define PUMPKIN_KEY_WORLD_1            161
#define PUMPKIN_KEY_WORLD_2            162

// Function Keys
#define PUMPKIN_KEY_ESCAPE             256
#define PUMPKIN_KEY_ENTER              257
#define PUMPKIN_KEY_TAB                258
#define PUMPKIN_KEY_BACKSPACE          259
#define PUMPKIN_KEY_INSERT             260
#define PUMPKIN_KEY_DELETE             261
#define PUMPKIN_KEY_RIGHT              262
#define PUMPKIN_KEY_LEFT               263
#define PUMPKIN_KEY_DOWN               264
#define PUMPKIN_KEY_UP                 265
#define PUMPKIN_KEY_PAGE_UP            266
#define PUMPKIN_KEY_PAGE_DOWN          267
#define PUMPKIN_KEY_HOME               268
#define PUMPKIN_KEY_END                269
#define PUMPKIN_KEY_CAPS_LOCK          280
#define PUMPKIN_KEY_SCROLL_LOCK        281
#define PUMPKIN_KEY_NUM_LOCK           282
#define PUMPKIN_KEY_PRINT_SCREEN       283
#define PUMPKIN_KEY_PAUSE              284
#define PUMPKIN_KEY_F1                 290
#define PUMPKIN_KEY_F2                 291
#define PUMPKIN_KEY_F3                 292
#define PUMPKIN_KEY_F4                 293
#define PUMPKIN_KEY_F5                 294
#define PUMPKIN_KEY_F6                 295
#define PUMPKIN_KEY_F7                 296
#define PUMPKIN_KEY_F8                 297
#define PUMPKIN_KEY_F9                 298
#define PUMPKIN_KEY_F10                299
#define PUMPKIN_KEY_F11                300
#define PUMPKIN_KEY_F12                301
#define PUMPKIN_KEY_F13                302
#define PUMPKIN_KEY_F14                303
#define PUMPKIN_KEY_F15                304
#define PUMPKIN_KEY_F16                305
#define PUMPKIN_KEY_F17                306
#define PUMPKIN_KEY_F18                307
#define PUMPKIN_KEY_F19                308
#define PUMPKIN_KEY_F20                309
#define PUMPKIN_KEY_F21                310
#define PUMPKIN_KEY_F22                311
#define PUMPKIN_KEY_F23                312
#define PUMPKIN_KEY_F24                313
#define PUMPKIN_KEY_F25                314
#define PUMPKIN_KEY_KP_0               320
#define PUMPKIN_KEY_KP_1               321
#define PUMPKIN_KEY_KP_2               322
#define PUMPKIN_KEY_KP_3               323
#define PUMPKIN_KEY_KP_4               324
#define PUMPKIN_KEY_KP_5               325
#define PUMPKIN_KEY_KP_6               326
#define PUMPKIN_KEY_KP_7               327
#define PUMPKIN_KEY_KP_8               328
#define PUMPKIN_KEY_KP_9               329
#define PUMPKIN_KEY_KP_DECIMAL         330
#define PUMPKIN_KEY_KP_DIVIDE          331
#define PUMPKIN_KEY_KP_MULTIPLY        332
#define PUMPKIN_KEY_KP_SUBTRACT        333
#define PUMPKIN_KEY_KP_ADD             334
#define PUMPKIN_KEY_KP_ENTER           335
#define PUMPKIN_KEY_KP_EQUAL           336
#define PUMPKIN_KEY_LEFT_SHIFT         340
#define PUMPKIN_KEY_LEFT_CONTROL       341
#define PUMPKIN_KEY_LEFT_ALT           342
#define PUMPKIN_KEY_LEFT_SUPER         343
#define PUMPKIN_KEY_RIGHT_SHIFT        344
#define PUMPKIN_KEY_RIGHT_CONTROL      345
#define PUMPKIN_KEY_RIGHT_ALT          346
#define PUMPKIN_KEY_RIGHT_SUPER        347
#define PUMPKIN_KEY_MENU               348