#pragma once

// From GLFW/glfw3.h
#define PUMPKIN_MOUSE_BUTTON_1         0
#define PUMPKIN_MOUSE_BUTTON_2         1
#define PUMPKIN_MOUSE_BUTTON_3         2
#define PUMPKIN_MOUSE_BUTTON_4         3
#define PUMPKIN_MOUSE_BUTTON_5         4
#define PUMPKIN_MOUSE_BUTTON_6         5
#define PUMPKIN_MOUSE_BUTTON_7         6
#define PUMPKIN_MOUSE_BUTTON_8         7
#define PUMPKIN_MOUSE_BUTTON_LAST      PUMPKIN_MOUSE_BUTTON_8
#define PUMPKIN_MOUSE_BUTTON_LEFT      PUMPKIN_MOUSE_BUTTON_1
#define PUMPKIN_MOUSE_BUTTON_RIGHT     PUMPKIN_MOUSE_BUTTON_2
#define PUMPKIN_MOUSE_BUTTON_MIDDLE    PUMPKIN_MOUSE_BUTTON_3